### ISSUE TITLE
How set value for KUBE_LOGTOSTDERR etc?

### ISSUE THREAD

**Issue by zdtsw** [cristifalcas/puppet-kubernetes#12]
Is there any way that  I can pass values to parameters, like:  KUBE_LOGTOSTDERR  KUBE_LOG_LEVEL KUBE_ALLOW_PRIV and KUBE_MASTER ( stated in templates/etc/kubernetes/config.erb) ?

I can see other templates erb files are using them, but this common config.erb looks more like a file than a template, 'coz no place for me to pass value into it

**Comment by cristifalcas** [comment]
KUBE_ALLOW_PRIV is for apiserver and kubelet only. Those classes have a parameter named "allow_privileged" that sets this:

```
class {'kubernetes::node::kubelet': allow_privileged => true}
class {'kubernetes::master::apiserver': allow_privileged => true}
```

For KUBE_MASTER it's the same as above: the classes that need the master set have a parameter for this. For kubelet the parameter name is "api_servers", for the others is "master".

KUBE_LOG_LEVEL can be set on each class by using the "verbosity" parameter.

KUBE_LOGTOSTDERR is not set anywhere. If you need this I can add it as a parameter also.

The module empties al variables from /etc/kubernetes/config because each class can be configured differently from the others regarding those parameters.
